### ISSUE TITLE
Memory loading indicator is located in the wrong place

### ISSUE THREAD

**Issue by Shished** [azeam/powerupp#11]
![image](https://user-images.githubusercontent.com/3143668/84899636-95f85000-b0b1-11ea-8e6b-0d2ca46c8fbf.png)

Built from source, launched on Arch with RX 5700.

**Comment by azeam** [comment]
Thanks for the report, I've noticed that the margins are rendered differently on different systems before but not this bad. Try this commit and see if it helps, remember to do a `make clean` before building with `make`

**Comment by Shished** [comment]
This fix helped, thanks.
![image](https://user-images.githubusercontent.com/3143668/84911911-7d903180-b0c1-11ea-8ac8-299d5b480659.png)
