### ISSUE TITLE
ModuleNotFoundError: No module named 'upp'

### ISSUE THREAD

**Issue by PNixx** [azeam/powerupp#13]
After click apply current I see in the terminal:
```
Values successfully loaded from pp table
Default file has 60 settings and there are 60 settings to write, not saving
Traceback (most recent call last):
  File "/home/nixx/.local/bin/upp", line 7, in <module>
    from upp.upp import main
ModuleNotFoundError: No module named 'upp'
```
Ubuntu 18.04.4

**Comment by azeam** [comment]
I believe this may be caused by initializing upp with Python2 (instead of Python3). Can you paste the output of  
`cat /home/nixx/.local/bin/upp`

**Comment by PNixx** [comment]
```
$ cat /home/nixx/.local/bin/upp
#!/usr/bin/python3

# -*- coding: utf-8 -*-
import re
import sys

from upp.upp import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

**Comment by PNixx** [comment]
I install a new ubuntu and install
```
sudo apt install git build-essential libgtk-3-dev build-essential python3 python3-pip libpci-dev && pip3 install upp
```
before make powerupp.
After make, run from terminal for see logs.

**Comment by azeam** [comment]
Thanks. Can you run upp from terminal (just type `upp` )?

Edit: if upp works, can you also paste the output of `pip3 show upp`?

**Comment by PNixx** [comment]
```
$ pip3 show upp
Name: upp
Version: 0.0.7
Summary: Uplift Power Play
Home-page: https://github.com/sibradzic/upp
Author: Samir Ibradžić
Author-email: None
License: UNKNOWN
Location: /home/nixx/.local/lib/python3.6/site-packages
Requires: click, python-registry
```

**Comment by azeam** [comment]
Pushed a new branch that I think should fix this, please try and let me know.

**Comment by PNixx** [comment]
No, I see same error

**Comment by azeam** [comment]
Ok, so likely not an issue with Python 2/3 (as was easily reproducible from my end, although not very logical) but probably an issue with missing library paths. Try this commit and see if it helps (not a fix, just need to understand what is going on).

**Comment by PNixx** [comment]
Yes, it works! Thanks

**Comment by azeam** [comment]
Do you have any thoughts on this @sibradzic ? For some reason that I have not fully understood yet, when starting upp via "bash -c ..." the PYTHONPATH, ie. the site-packages path where the upp library is located, is not available on a few systems (older Ubuntu?). The only way I seem to be able to set it up from powerupp is by immediately prepending the upp commands sent via Bash with PYTHONPATH=(each possible python version/site-packages) as in the test above, manually pre-setting the PYTHONPATH does not help as far as I can tell.

Do you see any better way to make sure the library path is found? Setting the path(s) in the upp bin, like `import site
site.addsitedir('/site-packages-path')` seems to work as well, but this file is created automatically by pip and not adjustable afaik?

**Comment by sibradzic** [comment]
I think the main issue here is calling local user installed pip Python stuff with sudo. As I've stated in https://github.com/sibradzic/upp/blob/master/README.md, this weird workaround should make things work: `sudo -E env "PATH=$PATH" upp --help`. @PNixx, try calling out `upp` as I mention locally first to see if it helps, as this could be distro-specific.

**Comment by azeam** [comment]
@sibradzic Thanks, the env trick does not seem to help in this case though (in fact it causes this very issue for me). I'm running upp as user with sudo -u, but I think the sudo call may very well have something to do with it if invokes a new shell but without the users paths, this would explain why it is not possible to set up before the very last call. Maybe adding an -i switch will invoke the new user shell from sudo with proper paths? Can you try this @PNixx

**Comment by PNixx** [comment]
Yes, latest commit https://github.com/azeam/powerupp/commit/e2ae4f48bf0cfd1ae4945e7e88458850487ae59c works fine.

**Comment by azeam** [comment]
@PNixx perfect, adding this to main branch, thanks to both of you!
