### ISSUE TITLE
Polkit authentication issue

### ISSUE THREAD

**Issue by fuzunspm** [azeam/powerupp#15]
Hi,

I can save and make it persistent without an error but it actually won't change anything according to the

`watch -n 0.5  cat /sys/kernel/debug/dri/0/amdgpu_pm_info`

and pp_od_clk_voltage file

I'm on kernel 5.7 with a 5700xt

and if i run powerupp from terminal, upon applying it asks for root password and after entering the correct password it outputs this error

```
==== AUTHENTICATING FOR org.freedesktop.policykit.exec ====
Authentication is needed to run `/usr/bin/bash' as the super user
Authenticating as: myusername
Password:
polkit-agent-helper-1: error response to PolicyKit daemon: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: No session for cookie
==== AUTHENTICATION FAILED ====
Error executing command as another user: Not authorized

This incident has been reported.
```

**Comment by azeam** [comment]
Which distro are you using? Can you run for example `pkexec pwd` in terminal?

**Comment by fuzunspm** [comment]
I'm using arch linux.

```
─$ pkexec pwd
/root
```

EDIT:

I temporarily fixed it by setting polkit password-less for my user group

**Comment by azeam** [comment]
Maybe try if this helps (old bug but with a recent commit) https://gitlab.freedesktop.org/polkit/polkit/-/issues/17 ?

**Comment by fuzunspm** [comment]
Since it's not related to powerupp and there is a temporary fix above in my comment, we can close this issue.
