### ISSUE TITLE
6800XT not recognized

### ISSUE THREAD

**Issue by asiantuntija** [azeam/powerupp#22]
Hi, I installed UPP from Git and PowerUPP from bignavi branch, launch options do have the amdgpu.ppmask=0xffffffff. PowerUPP doesn't open up any settings, saying "card 0: Unsupported AMD GPU".

UPP dump:
https://gist.github.com/asiantuntija/f2c8b3b5534f56f665366854ae6e6267

I never really got UPP working so don't know if the card is not supported there or there's something else going here.

**Comment by azeam** [comment]
The dump looks fine to me and the `header:
  [...]
  format_revision: 15` should be enough for powerupp to recognize the card. If you are 100% certain that you are running the bignavi branch (?) I suspect that powerupp tries to use the wrong UPP version, does `$(which upp) dump` give you the same output?

**Comment by asiantuntija** [comment]
Thanks for looking into this. `$(which upp) dump` gives the same output as `upp dump`. I installed PowerUPP this way:
`git clone https://github.com/azeam/powerupp.git`
`cd powerupp`
`git checkout bignavi`
`make`
`sudo make install`

Am I missing something here?

edit: When running powerupp on cli it outputs following:
`UPP path is /usr/bin/upp`
`GPU /sys/class/drm/card0/device/device exists`
`GPU 0 table revision is 15`

**Comment by azeam** [comment]
Looks good. Very strange, just confirm that the bignavi code is actually there, go to the cloned folder/src and do `cat main.c | grep bignavi` (output should not be empty) and re-install just in case. Otherwise there must be some extra blank space or something thrown in the output, I could try to change it to a pci id lookup instead later tonight if it doesn't work.

**Comment by asiantuntija** [comment]
It was a mistake on my end, there wasn't bignavi in the main.c file. Probably because I did a quick make before switching branch. Sorry for the inconvinience, I will now move on to testing the program, GPU is now detected and values read properly. And thanks for making this project and keeping up to date.

**Comment by azeam** [comment]
Sounds good, let me know how it works out for you!
