### ISSUE TITLE
AMD 6800XT Unsupported

### ISSUE THREAD

**Issue by koiakoia** [azeam/powerupp#26]
After installing via the Arch AUR I show card 0: Unsupported AMD GPU.

I have a 6800 XT that I am using and it works fine with all games and team red miner.

Maybe I do something not right?

kk

**Comment by sibradzic** [comment]
I have no idea who maintains AUR, please install with pip3 and report back...

**Comment by koiakoia** [comment]
That was indeed the issue.  The AUR needs updated.  Thank you and appologies for the waste of your time.  Thanks for your work.
