### ISSUE TITLE
6600xt Listed as Unsupported AMD GPU

### ISSUE THREAD

**Issue by ibrokemypie** [azeam/powerupp#29]
Using powerupp 94.5f9ed49 and upp 44.0fc77ca on linux 5.14 my XFX 6600xt is listed as unsupported in powerupp, however works fine in upp (at least for dumping values)

**Comment by azeam** [comment]
What is the output of `upp get header/format_revision`?

**Comment by ibrokemypie** [comment]
> What is the output of `upp get header/format_revision`?

```
upp get header/format_revision
18
```

**Comment by azeam** [comment]
Sorry for the late reply. Assuming the pp table has the same structure as 6800 [this tentative fix](https://github.com/azeam/powerupp/tree/test_6600) should work. If the limits seem off or something doesn't work, please share your `/sys/class/drm/cardX/device/pp_table` file. 

Edit: confirmed working for 6600, merged the fix to main branch.
