### ISSUE TITLE
RX 6600 (Non XT) Listed as Unsupported AMD GPU

### ISSUE THREAD

**Issue by juli2k8** [azeam/powerupp#30]
PowerColor RX 6600 (non XT version, Navi 23 XL) on Ubuntu 21.10 Kernel 5.13, listed as Unsupported AMD GPU.

upp get header/format_revision > Returns 18

**Comment by azeam** [comment]
Sorry for the late reply. Assuming the pp table has the same structure as 6800 [this tentative fix](https://github.com/azeam/powerupp/tree/test_6600) should work. If the limits seem off or something doesn't work, please share your `/sys/class/drm/cardX/device/pp_table` file.

**Comment by juli2k8** [comment]
running "make" there appears an error:
src/main.c:727:55: error: expected expression before ‘||’ token
  727 |               else if (strcmp(gpumodel,bignavi) == 0) || (strcmp(gpumodel,bignavi2) == 0) {

**Comment by juli2k8** [comment]
With the code reviewed, powerupp now detects my RX 6600 correctly
