### ISSUE TITLE
Navi 12 unsuported

### ISSUE THREAD

**Issue by Tradition2** [azeam/powerupp#33]
Good afternoon 
so upp just added support for v520 but powerupp is saying unsported GPu

the powertable is the same as 5700xt could u please check

**Comment by azeam** [comment]
Try [this branch](https://github.com/azeam/powerupp/tree/test_v520), not sure if the preset limits are correct so let me know if anything seems off.

**Comment by Tradition2** [comment]
Thank you so much seens to be working fine
