### ISSUE TITLE
RX 6700 XT Support

### ISSUE THREAD

**Issue by ndunks** [azeam/powerupp#35]
I see upp has support for Navi 22 (Navy Flounder), I think powerupp will support it also? I can provide some information that usefull for it:
`upp get header/format_revision` : 
```
16
```
pp_table of RX 6700 XT
https://github.com/ndunks/ndunks/blob/main/pp_table_rx_6700_xt.bin

Thanks for the great tool..

**Comment by azeam** [comment]
Thanks, seems to be of identical structure as the other 6000 series card, the latest version should work.

**Comment by ndunks** [comment]
Thanks, its detected..
