### ISSUE TITLE
ERROR : invalid parameter "header"

### ISSUE THREAD

**Issue by archit3kt** [azeam/powerupp#37]
Hello,

I just installed powerupp on latest fresh manjaro with pamac build powerupp-git, trying to OC 2 Vega cards (one 56 and one 64)

When I lauch powerupp in console, I've got a strange error message : 

UPP path is /usr/bin/upp
GPU /sys/class/drm/card0/device/device exists
GPU 0 table revision is ERROR: Invalid parameter "header", available ones are : sHeader, TableRevision, TableSize, GoldenPPID, GoldenRevision, FormatID,GPU /sys/class/drm/card1/device/device exists

Result is my 2 cards are shown as "Unsupported AMD GPU"

Any help appreciated :)

**Comment by azeam** [comment]
Forgot about this issue, sorry. The reason is that Vega cards are not supported by PowerUPP, though you can use UPP.
