### ISSUE TITLE
Linux 5.17 /sys card numbering breaks PowerUPP

### ISSUE THREAD

**Issue by iserlohn** [azeam/powerupp#38]
After upgrade to the latest Fedora Rawhide kernel 5.17-rc6, /sys card numbering starts from 1 instead of 0 (e.g. /sys/class/drm/card1).

This breaks PowerUPP as the scan_gpus() function main.c has a while loop starting from card0 and end when there is no card found.

Below is the patch I made to make it work again. Basically, it adds a "Card0: Not Available" entry to the combobox if card0 is not found, and then tries card1 as normal.

I've tested it and it works fine for me so far.

https://gist.github.com/iserlohn/dd0d90039db06743fdf5baec21b684ee

**Comment by azeam** [comment]
Thanks for the report and sorry for the late reply. I don't have access to my main computer at the moment, perhaps something like this right before the loop could work instead?

`if (access("/sys/class/drm/card0/device/device", F_OK) == -1) {
  num = 1;
}`

**Comment by b310v3** [comment]
Same issue here. latest update change the index from 0 to 1, and PowerUPP can't read anything.

**Comment by azeam** [comment]
Can you try [this branch](https://github.com/azeam/powerupp/tree/fix-sys-card-numbering) if see it fixes the issue?

**Comment by b310v3** [comment]
Yup I just test it and it work!

**Comment by azeam** [comment]
Thanks, merged it to main branch
