### ISSUE TITLE
Radeon 5700XT power limit increase doesn't work

### ISSUE THREAD

**Issue by Smokolak** [azeam/powerupp#7]
Hi,
I'm a user of 5700XT, reading from my device says that I got 180W maxcap for power, I tried to apply 200W but it fails. I was wondering if it's supportedd for Navi? I'm running furmark to test it and readings in you gui are always about 180W. Doesn't matter if I increase or decrease it. Using Solus 5.6.13-153 kernel

**Comment by azeam** [comment]
Most likely #3 , see workaround there

**Comment by Smokolak** [comment]
Ok, thanks, looks like this bug persists for me. Also when I apply the changes /sys/class/drm/card0/device/hwmon/hwmon3/power1_cap file is updated but after restart it goes to default GPU setting

**Comment by azeam** [comment]
You can try to download `https://archive.archlinux.org/packages/l/linux-firmware/linux-firmware-20191220.6871bff-1-any.pkg.tar.xz` and copy the files in `/usr/lib/firmware/amdgpu/` from that file to the same folder on your computer with sudo/root (the files starting with `navi10` are enough, and make a backup of existing files just in case something would go wrong). Hopefully this will get fixed for all systems soon enough, not much I can do from my end though. For the settings to stay active after restart you need to use the "persistent save" option.

**Comment by Smokolak** [comment]
Ok. Thanks!

**Comment by Shished** [comment]
@Smokolak Did it helped to you? @azeam did not mentioned that you also will have to recreate the initrd image so that needed firmware is included in it and loaded during boot up by kernel.

This bug report should be closed because it is not this programs fault.

**Comment by Smokolak** [comment]
@Shished yeah I sorted it out, thanks!!! @azeam thanks!!!
