### ISSUE TITLE
issue compileing on arch

### ISSUE THREAD

**Issue by xnuken** [azeam/powerupp#8]
i have all the deps installed 

https://bin.disroot.org/?d2bae67f933e1d00#B6oZbiHouu1MmpnCtcVSnqB2A8DCaPSEkWvq9BXFHc9p

**Comment by azeam** [comment]
Can you try this testbranch and see if it helps?

**Comment by xnuken** [comment]
sure let me download it

**Comment by xnuken** [comment]
yep that seemed to fix the issue built without any issue and runs fine

**Comment by azeam** [comment]
Great, will add the changes to main branch!

**Comment by xnuken** [comment]
thank you!
